"""Claim Check 016 report. Run calc.py and figures.py first. Output: out/report.pdf"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from mizien_report import *  # noqa: E402,F401

FIG = HERE / "out"
S = []

# ================================================================== TL;DR
S += [SectionHeading(None, "TL;DR"), Spacer(1, 1 * mm),
      P("Infrastructure Malta’s project page for the Grand Harbour shore-to-ship system says the EUR 33 million "
        "initiative <b>“promises to slash 90% of air pollution in the Grand Harbour”</b>. At the July 2024 inauguration "
        "the government said its completion meant a 90% cut and cleaner air for 17,000 families. We tested the figure "
        "against how the system is actually used, the law that governs it, and peer-reviewed research on cruise "
        "emissions in port.", lead)]
S.append(key_points([
    ("Shore power works for a ship that plugs in.",
     "A cruise liner connected to the grid can switch off its auxiliary engines; its exhaust at the quay stops. "
     "Research finds that time at berth (hotelling) produces most of a cruise ship’s emissions in port."),
    ("But plugging in is voluntary until 2030.",
     "EU law (FuelEU Maritime, Art. 6) only makes connection compulsory from 1 January 2030. Transport Malta says "
     "connecting “remains the prerogative of the shipping line”. Neither the project page nor the launch said so."),
    ("In its first year, ships plugged in for 9% of their time at berth.",
     "Transport Malta records obtained by Amphora Media show 67 connections in 373 berths (18%) from July 2024 to "
     "July 2025; one ship made half of them. No ship staying two days or more plugged in."),
    ("Cruise traffic grew.",
     "Calls rose from 357 (2024) to 385 (2025). At first-year uptake, the extra calls roughly cancel the "
     "emissions saved. No air-quality study has measured the effect in the harbour."),
    ("Verdict: misleading (moderate confidence).",
     "The 90% describes what happens when every ship connects. Presented as a result of completing the project, "
     "it omits the voluntary connection and actual use, which the evidence puts nearer a tenth of the claim."),
]))
S += [Spacer(1, 4 * mm), VerdictMeter(3), Spacer(1, 3 * mm),
      tiles([("90%", GREY, "Cut promised for Grand Harbour air pollution (Infrastructure Malta)"),
             ("18%", ORANGE, "Cruise berths that plugged in, Jul 2024–Jul 2025"),
             ("9%", RED, "Share of berth time plugged in (upper bound on the cut)"),
             ("2030", GREEN, "Year EU law makes plugging in compulsory")]),
      Spacer(1, 4 * mm),
      up_down("Connection logs showing most berth time is now plugged in, or a measured fall in harbour NO2 and "
              "particulates of the claimed size, controlled for traffic and weather.",
              "Evidence that the 2024–25 uptake figures overstate use, or that the claimed 90% was always stated "
              "with the condition that ships connect (we found no such wording)."),
      Spacer(1, 5 * mm)]
S += toc([("1", "The claim and what we could verify"), ("2", "Method"), ("3", "What the research says"),
          ("4", "How the system is used"), ("5", "Where the evidence points different ways"),
          ("6", "Testing the claim"), ("7", "Verdict and requests for evidence"), ("8", "Limitations")])
S.append(PageBreak())

# ================================================================== 1
S.append(SectionHeading(1, "The claim and what we could verify"))
S.append(P("The claim is on Infrastructure Malta’s project page, published on 1 December 2023 when the first ships "
           "were connected in a trial [1]. It was repeated at the inauguration on 10 July 2024, reported by TVM, the "
           "public broadcaster [2], and by MaltaToday [3]. The project page was read in full; the press conference "
           "is known through reported speech."))
S.append(std_table([
    [C("What was said", cellh), C("Who", cellh), C("Access", cellh)],
    [C("“This initiative promises to slash 90% of air pollution in the Grand Harbour.”"),
     C("Infrastructure Malta [1]"), C("Read in full")],
    [C("Completion “means a drastic reduction of 90% of the pollution generated by ships entering the Grand Harbour”"),
     C("Press conference, as reported [2]"), C("Reported speech")],
    [C("17,000 families around the harbour “will directly benefit” from cleaner air"),
     C("Prime Minister, as reported [2]"), C("Reported speech")],
    [C("90% when five liners use the system at once"), C("Press conference, as reported [3]"),
     C("Summary read")],
], [104 * mm, 38 * mm, 28 * mm]))
S += [Spacer(1, 4 * mm),
      callout([P("SCOPE NOTE", tag),
               P("This check is about the 90% figure. It does not question that shore power is worth building, and it "
                 "does not assess the electricity supply, the grid outages alleged in 2025 (denied by Transport Malta "
                 "and Enemalta), or noise.", small)], bg=AMBER_PALE, bar=AMBER), Spacer(1, 4 * mm)]

# ================================================================== 2
S.append(SectionHeading(2, "Method"))
S.append(P("<b>Question.</b> Has, or will, the shore-to-ship project cut Grand Harbour air pollution by 90%?"))
S.append(P("<b>Evidence.</b> The project page and launch reports [1–3]; connection records for July 2024 to July 2025 "
           "obtained by Amphora Media from Transport Malta under freedom of information [4] (second-hand: the reply "
           "is not public); Valletta Cruise Port’s traffic figures [5]; Regulation (EU) 2023/1805 [6]; peer-reviewed "
           "studies found through Crossref and OpenAlex [7–9]. Numbers are recomputed by "
           "<i>tools/cc-016-report/calc.py</i> from <i>data/cc-016/</i>."))
S.append(P("<b>Grades.</b> Peer-reviewed observational studies are grade B; official records and reviews grade C. "
           "◆ marks data known second-hand. <b>Verdicts</b> follow the five-point scale in Appendix A."))

# ================================================================== 3
S.append(CondPageBreak(80 * mm))
S.append(SectionHeading(3, "What the research says"))
S.append(P("A bottom-up inventory of 164 cruise calls at Istanbul’s Galataport in 2024 found that hotelling, the time "
           "at berth with auxiliary engines running, produced more than 90% of the ships’ CO2 in port and most of their "
           "NOx and SOx [7]. Shore power targets exactly that phase, which is why a figure near 90% is plausible "
           "<i>for a ship that connects</i>. Emissions do not disappear: they move to the power station supplying the "
           "grid."))
S.append(P("Shore power does nothing for manoeuvring. A sensor network in the Bay of Kotor found particulate spikes "
           "when cruise ships arrived and departed [8], and a 2025 review lists cost, ship retrofits and voluntary "
           "use among the barriers to adoption [9]. Pollution in the harbour also comes from ferries, tugs, "
           "other ships, road traffic and the power station; the claim speaks of all air pollution in the Grand "
           "Harbour."))

# ================================================================== 4
S.append(CondPageBreak(150 * mm))
S.append(SectionHeading(4, "How the system is used"))
S.append(fig(FIG / "fig1_uptake.png"))
S.append(P("Figure 1. Left: the promised cut against the share of berths and of berth time plugged in during the "
           "first year. Right: plug-in rate by length of stay. Data ◆ [4].", cap))
S.append(fig(FIG / "fig2_calls.png"))
S.append(P("Figure 2. Cruise calls at Valletta Cruise Port [5]; 2019–2023 as quoted in [4].", cap))
S.append(std_table([
    [C("Indicator", cellh), C("Value", cellh), C("Source", cellh), C("Grade", cellh)],
    [C("Berths plugged in, Jul 2024–Jul 2025"), C("<b>67 of 373 (18%)</b>"), C("Transport Malta FOI ◆ [4]"), grade_tag("C")],
    [C("Share of berth time plugged in"), C("<b>9%</b>"), C("Amphora Media analysis ◆ [4]"), grade_tag("C")],
    [C("Connections by MSC World Europa"), C("35 of 67 (52%)"), C("Transport Malta FOI ◆ [4]"), grade_tag("C")],
    [C("Carnival Corporation calls plugged in"), C("6 of 58"), C("Transport Malta FOI ◆ [4]"), grade_tag("C")],
    [C("Stays of 2–4 days plugged in"), C("0%"), C("Amphora Media analysis ◆ [4]"), grade_tag("C")],
    [C("Cruise calls 2024 → 2025"), C("357 → 385 (+8%)"), C("Valletta Cruise Port [5]"), grade_tag("C")],
    [C("Connection compulsory from"), C("1 Jan 2030"), C("Reg. (EU) 2023/1805 Art. 6 [6]"), grade_tag("C")],
], [70 * mm, 38 * mm, 50 * mm, 12 * mm]))
S.append(P("All values in <i>data/cc-016/checks.csv</i>. Transport Malta said Carnival’s connections were for testing "
           "and certification, after which its ships “will be able to use the system routinely” [4].", cap))

# ================================================================== 5
S.append(CondPageBreak(120 * mm))
S.append(SectionHeading(5, "Where the evidence points different ways"))
S.append(contested(
    "Q1  Is 90% the right number for a connected ship?", "PLAUSIBLE", GREENC,
    "Hotelling dominates cruise emissions in port [7]; a ship on shore power emits nothing from its auxiliary engines "
    "at the quay. A 90% cut in that ship’s local emissions is consistent with the research.",
    "No source gives the basis of the 90% (which pollutant, which ships, what share of time). Manoeuvring "
    "emissions remain [8].",
    "<b>For this claim:</b> the figure is defensible as an engineering potential per connected ship."))
S.append(contested(
    "Q2  Did completion of the project deliver 90%?", "NO", RED,
    "Use is rising: one large ship plugs in routinely, and Carnival ships were certifying in 2025 [4].",
    "Ships were plugged in for 9% of berth time in the first year; with 100% removal while plugged in, the cut in "
    "at-berth cruise emissions could be at most about 9%. Calls rose 8% in 2025.",
    "<b>For this claim:</b> presented as a result of completion, the 90% overstates the first-year effect about "
    "tenfold."))
S.append(contested(
    "Q3  Will it reach 90%?", "NOT BEFORE 2030", AMBER,
    "From 2030 EU law requires passenger ships at berth in core ports to connect [6], which could bring use close "
    "to the design potential.",
    "Until then connection is the shipping line’s choice; the law has exemptions (for example grid stability).",
    "<b>For this claim:</b> a future 90% depends on the 2030 obligation, not on completing the project."))

# ================================================================== 6
S.append(CondPageBreak(110 * mm))
S.append(SectionHeading(6, "Testing the claim"))
verd = lambda t, c: chip(t, c, w=29 * mm)
S.append(std_table([
    [C("Sub-claim", cellh), C("What the evidence shows", cellh), C("Rating", cellh)],
    [C("<b>A.</b> Shore power cuts a connected ship’s emissions at berth by about 90%"),
     C("Consistent with research on hotelling emissions [7, 9]; basis of the figure not published."),
     verd("PLAUSIBLE", GREENC)],
    [C("<b>B.</b> The project slashes 90% of air pollution in the Grand Harbour"),
     C("At most about 9% of at-berth cruise emissions in year one; other sources and manoeuvring untouched; "
       "no harbour measurement."), verd("NOT SHOWN", RED)],
    [C("<b>C.</b> 17,000 families benefit from cleaner air"),
     C("Basis of the figure not found; any benefit scales with use."), verd("NOT SHOWN", GREY)],
    [C("<b>D.</b> EUR 33 million; 17 points; five liners at once"),
     C("Consistent across official sources [1–3]."), verd("CONSISTENT", GREENC)],
], [52 * mm, 88 * mm, 30 * mm], valign="MIDDLE"))

# ================================================================== 7
S += [Spacer(1, 6 * mm), SectionHeading(7, "Verdict and requests for evidence"),
      verdict_box("Misleading", "A design potential presented as a result; connection is voluntary until 2030 and "
                  "first-year use was 9% of berth time. Confidence: moderate."), Spacer(1, 4 * mm)]
S.append(P("<b>Why.</b> (1) The 90% is plausible only for ships that plug in. (2) The project page and launch "
           "presented it as what the project does, without saying that connection is voluntary until 2030 [1, 2, 6]. "
           "(3) Transport Malta’s own records, as reported, show ships plugged in for 9% of berth time in the first "
           "year [4], so the cut was roughly a tenth of the figure claimed. The individual facts (cost, connection "
           "points, capacity) are accurate; the overall impression is not. Our scale calls this <i>Misleading</i>."))
S.append(P("<b>Confidence is moderate</b> because the connection records are known through a news analysis, not "
           "the FOI reply itself, and no air-quality measurement exists either way."))
S.append(P("Evidence we are asking for", h2))
S.append(requests_list([
    "Transport Malta’s OPS connection log by call and hours, July 2024 to date.",
    "The calculation behind the 90% and 17,000-family figures.",
    "The results of ERA’s Senglea shipping study (mobile station, until October 2024).",
    "The shore power agreements’ terms on use, which Transport Malta declined to release as commercial.",
]))

# ================================================================== 8
S += [Spacer(1, 6 * mm), SectionHeading(8, "Limitations")]
for l in ["Connection figures are second-hand (Amphora Media’s analysis of a Transport Malta FOI reply) ◆.",
          "The 9% upper bound assumes zero local emissions while plugged in and the same mix of ships plugged and "
          "unplugged; larger ships plugging in could make the cut in tonnes somewhat larger.",
          "Uptake may have risen since July 2025; no later figures were found.",
          "Emissions shifted to the power station and the interconnector were not estimated.",
          "Peer-reviewed papers were read as abstracts."]:
    S.append(P("• " + l, bul))

S += [Spacer(1, 6 * mm), SectionHeading(None, "References")]
S += references([
    ("1", "Infrastructure Malta (1 Dec 2023). Shore-to-Ship. Project page.",
     "https://www.infrastructuremalta.com/projects/shore-ship"),
    ("2", "TVMnews (10 Jul 2024). Grand Harbour shore-to-ship project completed, to cut down emissions by 90%.",
     "https://tvmnews.mt/en/news/shore-to-ship-project-in-grand-harbour-completed-to-cut-down-emissions-by-90/"),
    ("3", "MaltaToday (10 Jul 2024). Grand Harbour’s shore-to-ship project launched.",
     "https://www.maltatoday.com.mt/news/national/130180/grand_harbours_shoretoship_project_launched"),
    ("4", "Demarco J. (17 Oct 2025). Cruise ships plugged in Grand Harbour onshore power supply only 9% of time in "
          "first year. <i>Amphora Media</i>. ◆ Transport Malta FOI data.",
     "https://www.amphora.media/2025/10/cruise-ships-shore-to-ship-power-malta"),
    ("5", "Valletta Cruise Port (2026). Valletta Cruise Port closes 2025 with strong growth and nearly one million "
          "passenger movements.",
     "https://www.vallettacruiseport.com/news-media/valletta-cruise-port-closes-2025-with-strong-growth-and-nearly-one-million-passenger-movements"),
    ("6", "Regulation (EU) 2023/1805 (FuelEU Maritime), Article 6. OJ L 234, 22.9.2023.",
     "https://eur-lex.europa.eu/eli/reg/2023/1805/oj"),
    ("7", "Mocerino L., Ergin S., Temren G. (2026). Emission inventory of cruise ship exhaust emissions at Istanbul "
          "Galataport (2024). <i>Atmosphere</i> 17(4):360. doi:10.3390/atmos17040360. (Abstract read.)",
     "https://doi.org/10.3390/atmos17040360"),
    ("8", "Gagić R., Škuric M., Djukanović G., Nikolić D. (2022). Establishing correlation between cruise ship "
          "activities and ambient PM concentrations in the Kotor Bay area. <i>Atmosphere</i> 13(11):1819. "
          "doi:10.3390/atmos13111819. (Abstract read.)", "https://doi.org/10.3390/atmos13111819"),
    ("9", "Rogošić M., Stanivuk T., Lucaci D. (2025). A study on the application of shore-side power as a method to "
          "reduce the emissions of greenhouse gases by cruise ships. <i>J. Marine Science and Engineering</i> "
          "13(3):453. doi:10.3390/jmse13030453. (Abstract read.)", "https://doi.org/10.3390/jmse13030453"),
    ("10", "MiŻien. Data and calculations: data/cc-016/; tools/cc-016-report/calc.py.", ""),
])

S.append(PageBreak())
S += appendix_a("A experiment · B observational study with a control or gradient · C review, guidance or "
                "official statistics · D assertion or anecdote. ◆ marks a source known only second-hand.")
S += [Spacer(1, 5 * mm)]
S += revision_log([("1.0", "3 Oct 2026", "First issue. Right of reply to Infrastructure Malta and Transport Malta "
                    "not yet sent.")])

build_report(Report(
    number="016", out=str(FIG / "report.pdf"), kicker="Air quality",
    title_lines=["Does shore power", "cut harbour", "pollution by 90%?"],
    subtitle_lines=["Testing a public claim about the Grand Harbour shore-to-ship project",
                    "against connection records, EU law and research"],
    quote_lines=["“This initiative promises to slash 90%", "of air pollution in the Grand Harbour.”"], quote_size=16,
    attribution="Infrastructure Malta, Shore-to-Ship project page, 1 December 2023.",
    context="Repeated at the inauguration, 10 July 2024.",
    verdict="Misleading", verdict_note="A design potential presented as a result; ships plugged in 9% of the time",
    footer_lines=["Version 1.0  ·  3 October 2026", "Status: draft (right of reply: Infrastructure Malta, Transport Malta)",
                  "Prepared from public sources and published records.", "Repository: github.com/leandergrech/Mizien"],
    running_head="Shore-to-ship and harbour air – Malta", version="1.0", date="3 October 2026",
    pdf_title="Does shore power cut harbour pollution by 90%? Claim Check 016",
    pdf_subject="Tests Infrastructure Malta's claim that shore-to-ship slashes 90% of Grand Harbour air pollution",
    story=S))
