"""The tracker sheets, generated from the claim records so they cannot drift from them.

claims/CC-NNN/claim.yml is the source of truth. This module writes what is derived from it:

  data/claims.csv     the claim sheet: one row per claim (columns of the original tracker)
  data/facts.csv      the fact sheet: every figure recomputed by a check, from data/cc-nnn/checks.csv
  data/actors.csv     bodies and the claims they made, from the register (data/bodies.csv)
  data/themes.csv     only its "Edges generated" column (recounted from data/edges.csv); themes are curated by hand
  README.md           the claims table, between the <!-- claims-table --> markers
  data/candidates.xlsx  the workbook (python scripts/sheets.py --xlsx): every sheet above plus quick checks,
                        patterns, edges, sources, bodies and the queue, for reading in a spreadsheet

Hand-curated, read here but never written: data/edges.csv, data/sources.csv, data/quick_checks.csv,
data/queue.csv, data/bodies.csv, methodology/pattern-tags.md.

scripts/build_site_data.py calls write_text_sheets() on every build, so the CSV sheets and the README table follow
the records. The workbook is binary (it cannot be merged), so it is rebuilt on request, at the end of a session:

    python scripts/sheets.py           # text sheets only
    python scripts/sheets.py --xlsx    # text sheets and data/candidates.xlsx
"""
import collections
import csv
import io
import pathlib
import re
import sys
import zipfile

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import bodies as register  # noqa: E402

SITE = "https://leandergrech.github.io/Mizien"
CLAIM_COLUMNS = ["ID", "Category", "Short title", "Claim and who made it", "Counter-evidence or context",
                 "Test it against", "Why it is low-hanging", "Pattern tag (provisional)", "Body / actor",
                 "Claim wording status", "Data readiness", "Priority", "Caveats", "Check status",
                 "Right of reply sent (date)", "Linked claims (count)", "Notes"]
FACT_COLUMNS = ["ID", "Row", "Check", "Value", "Unit", "Source", "Note", "Other fields"]
ACTOR_COLUMNS = ["Body / actor", "Claim IDs", "Type", "Claims (count)"]
REPLY_VERDICTS = {"Not substantiated", "Misleading", "Contradicted"}       # a right of reply is sought (5 Oct 2026)
REPLY_PLEDGES = {"Not measurable", "Off track", "Missed"}
TABLE_START, TABLE_END = "<!-- claims-table: generated by scripts/sheets.py -->", "<!-- /claims-table -->"


# ---------------------------------------------------------------- reading

def load_records():
    return [yaml.safe_load(p.read_text(encoding="utf-8")) for p in sorted((ROOT / "claims").glob("CC-*/claim.yml"))]


def read_csv(name):
    path = ROOT / "data" / name
    if not path.is_file():
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_csv(path, header, rows):
    """CRLF line endings, as the hand-kept CSVs use; written only when the content changes."""
    buf = io.StringIO(newline="")
    w = csv.writer(buf, lineterminator="\r\n")
    w.writerow(header)
    w.writerows([[("" if r.get(c) is None else r.get(c)) for c in header] for r in rows])
    data = buf.getvalue().encode("utf-8")
    if not path.is_file() or path.read_bytes() != data:
        path.write_bytes(data)
        return True
    return False


def text(v):
    return re.sub(r"\s+", " ", str(v)).strip() if v not in (None, "") else ""


def neighbours(edges):
    adj = collections.defaultdict(set)
    for e in edges:
        if e["From"] != e["To"]:
            adj[e["From"]].add(e["To"])
            adj[e["To"]].add(e["From"])
    return adj


def pledge_label(d):
    p = d.get("pledge")
    return p.get("status") if isinstance(p, dict) else None


def verdict_text(d):
    """As in the README table: 'Largely supported (pledge: Off track)', 'Pledge: Not measurable' or '-'."""
    v, p = d.get("verdict"), pledge_label(d)
    if v and p:
        return f"{v} (pledge: {p})"
    return v or (f"Pledge: {p}" if p else "-")


def reply_state(d):
    rr = d.get("right_of_reply") or {}
    if rr.get("response"):
        return "reply received"
    if rr.get("sent"):
        return f"right of reply sent {rr['sent']}" + (f", deadline {rr['deadline']}" if rr.get("deadline") else "")
    if d.get("verdict") in REPLY_VERDICTS or pledge_label(d) in REPLY_PLEDGES:
        return "right of reply to send (draft; not for circulation before the deadline)"
    return "no right of reply needed"


def notes(d, queue_row):
    """A derived status line: the report and verdict for a drafted check, the blocker for a started one."""
    if d.get("status") in ("Drafted", "Right of reply", "Published"):
        bits = [f"Report v{d['version']}" if d.get("version") else "Report"]
        if d.get("verdict"):
            conf = f" ({str(d['verdict_confidence']).lower()})" if d.get("verdict_confidence") else ""
            bits.append(f"verdict {d['verdict']}{conf}")
        if pledge_label(d):
            bits.append(f"pledge {pledge_label(d)}")
        bits.append(reply_state(d))
        return "; ".join(bits) + "."
    blocker = (queue_row or {}).get("Blocker", "").strip()
    if blocker:
        return f"Worker {queue_row['Worker']}, attempt {queue_row['Attempts']} ({queue_row['Last attempt']}): {blocker}"
    if queue_row:
        return f"Queued for worker {queue_row['Worker']}."
    return ""


# ---------------------------------------------------------------- sheets

def claim_rows(records, edges, queue):
    adj = neighbours(edges)
    rows = []
    for d in records:
        c = d.get("claim") or {}
        rows.append({
            "ID": d["id"], "Category": d.get("category"), "Short title": d.get("title"),
            "Claim and who made it": text(c.get("text")), "Counter-evidence or context": text(d.get("counter_evidence")),
            "Test it against": text(d.get("tests")), "Why it is low-hanging": text(d.get("why_low_hanging")),
            "Pattern tag (provisional)": "; ".join(d.get("tags") or []), "Body / actor": text(c.get("speaker")),
            "Claim wording status": c.get("wording_status"), "Data readiness": d.get("data_readiness"),
            "Priority": d.get("priority"), "Caveats": text(d.get("caveats")), "Check status": d.get("status"),
            "Right of reply sent (date)": (d.get("right_of_reply") or {}).get("sent"),
            "Linked claims (count)": len(adj.get(d["id"], ())), "Notes": notes(d, queue.get(d["id"])),
        })
    return rows


def _fact(cid, line, row, header):
    """One check row in the fact sheet's columns; columns of other layouts are kept in 'Other fields'."""
    used = set()

    def take(*keys):
        for k in keys:
            if k in row and k not in used:
                used.add(k)
                return text(row[k])
        return ""
    check = take("check")
    if not check:
        first = header[0]
        check = f"{first}: {take(first)}"
    year = take("year")
    if year:
        check += f" ({year})"
    value = take("value", "recomputed")
    unit = take("unit")
    source = take("source")
    retrieved = take("retrieved", "retrieved_date")
    if retrieved:
        source = f"{source} (retrieved {retrieved})" if source else f"retrieved {retrieved}"
    note = take("note")
    other = "; ".join(f"{k}: {text(row[k])}" for k in header if k not in used and text(row.get(k)))
    return {"ID": cid, "Row": f"{cid}:{line}", "Check": check, "Value": value, "Unit": unit, "Source": source,
            "Note": note, "Other fields": other}


def fact_rows():
    """Every row of every data/cc-nnn/checks.csv. Row is CC-NNN:line, the header being line 1 (as the fact ledger)."""
    out = []
    for path in sorted((ROOT / "data").glob("cc-*/checks.csv")):
        cid = "CC-" + path.parent.name[3:]
        with open(path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if any(text(v) for v in row.values()):   # line_num: the file's own line (header = 1)
                    out.append(_fact(cid, reader.line_num, row, reader.fieldnames))
    return out


def actor_rows(records, reg):
    """Each organisation with the claims made by it or its people (the register's own grouping)."""
    idx = register.alias_index(reg)
    by_org = collections.defaultdict(list)
    for d in records:
        for bid in register.resolve(d, reg, idx)[0]:
            org = register.org_of(bid, reg)
            if d["id"] not in by_org[org]:
                by_org[org].append(d["id"])
    rows = [{"Body / actor": reg[o]["name"], "Claim IDs": ", ".join(sorted(ids)),
             "Type": register.TYPES.get(reg[o]["type"], reg[o]["type"]), "Claims (count)": len(ids)}
            for o, ids in by_org.items() if o in reg]
    return sorted(rows, key=lambda r: (-r["Claims (count)"], r["Body / actor"]))


def themes_recounted(themes, edges):
    n = collections.Counter(e["Theme ID"] for e in edges)
    return [{**t, "Edges generated": str(n.get(t["Theme ID"], 0))} for t in themes]


def readme_table(records):
    counts = collections.Counter(d.get("status") for d in records)
    order = ["Published", "Right of reply", "Drafted", "In progress", "Not started"]
    summary = ", ".join(f"{counts[s]} {s.lower()}" for s in order if counts[s])
    lines = [TABLE_START, "",
             f"{len(records)} claims ({records[0]['id']} to {records[-1]['id']}): {summary}. Generated from each "
             "claim's `claim.yml` by `scripts/sheets.py`; edit the records, not this table.", "",
             "| ID | Topic | Claim | Status | Verdict |", "|---|---|---|---|---|"]
    lines += [f"| {d['id']} | {d.get('category')} | {d.get('title')} | {d.get('status')} | {verdict_text(d)} |"
              for d in records]
    return "\n".join(lines + ["", TABLE_END])


def write_readme(records):
    path = ROOT / "README.md"
    s = path.read_text(encoding="utf-8")
    if TABLE_START not in s:
        return False
    new = re.sub(re.escape(TABLE_START) + r".*?" + re.escape(TABLE_END), lambda m: readme_table(records), s,
                 count=1, flags=re.S)
    if new != s:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def write_text_sheets(records=None):
    """The CSV sheets and the README table. Returns the paths that changed."""
    records = records or load_records()
    edges, themes = read_csv("edges.csv"), read_csv("themes.csv")
    queue = {r["ID"]: r for r in read_csv("queue.csv")}
    reg = register.load()
    changed = []
    data = ROOT / "data"
    if write_csv(data / "claims.csv", CLAIM_COLUMNS, claim_rows(records, edges, queue)):
        changed.append("data/claims.csv")
    if write_csv(data / "facts.csv", FACT_COLUMNS, fact_rows()):
        changed.append("data/facts.csv")
    if write_csv(data / "actors.csv", ACTOR_COLUMNS, actor_rows(records, reg)):
        changed.append("data/actors.csv")
    if themes and write_csv(data / "themes.csv", list(themes[0].keys()), themes_recounted(themes, edges)):
        changed.append("data/themes.csv")
    if write_readme(records):
        changed.append("README.md")
    return changed


# ---------------------------------------------------------------- workbook

def pattern_rows(records):
    md = (ROOT / "methodology" / "pattern-tags.md").read_text(encoding="utf-8")
    tags = re.findall(r"^\|\s*\*\*(.+?)\*\*\s*\|\s*(.+?)\s*\|\s*$", md, flags=re.M)
    rows = []
    for tag, meaning in tags:
        mine = [d for d in records if tag in (d.get("tags") or [])]
        final = [d["id"] for d in mine if not d.get("tags_provisional", True)]
        prov = [d["id"] for d in mine if d.get("tags_provisional", True)]
        verdicts = collections.Counter(verdict_text(d) for d in mine if verdict_text(d) != "-")
        rows.append({"Tag": tag, "Meaning": meaning, "Claims (finished reports)": ", ".join(final),
                     "Claims (provisional)": ", ".join(prov), "Claims (count)": len(mine),
                     "Verdicts of tagged claims": "; ".join(f"{v} {n}" for v, n in verdicts.most_common())})
    return rows


def quick_check_formula(r, n):
    """The arithmetic that turns the two inputs into 'Calculated', when one of the usual operations reproduces it."""
    try:
        a, b, calc = float(r["Value 1"]), float(r["Value 2"]), float(str(r["Calculated"]).rstrip("%"))
    except (TypeError, ValueError):
        return None
    pct = str(r["Calculated"]).endswith("%")
    ops = [(f"=D{n}*F{n}", a * b), (f"=ROUND(D{n}*F{n},0)", round(a * b)), (f"=D{n}+F{n}", a + b),
           (f"=D{n}-F{n}", a - b), (f"=F{n}-D{n}", b - a), (f"=D{n}/F{n}", a / b if b else None),
           (f"=(F{n}-D{n})/D{n}", (b - a) / a if a else None)]
    for formula, v in ops:
        if v is None:
            continue
        target = calc / 100 if pct else calc
        if abs(v - target) <= 1e-9 * max(1, abs(target)) or (pct and round(v * 100, 1) == calc):
            return formula
    return None


def write_workbook(records, path=None):
    from openpyxl import Workbook
    from openpyxl.formatting.rule import CellIsRule
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation

    path = path or ROOT / "data" / "candidates.xlsx"
    edges, themes = read_csv("edges.csv"), read_csv("themes.csv")
    queue = {r["ID"]: r for r in read_csv("queue.csv")}
    reg = register.load()
    head_fill, head_font = PatternFill("solid", fgColor="14452F"), Font(bold=True, color="FFFFFF", name="Liberation Sans")
    body_font, input_font = Font(name="Liberation Sans", size=10), Font(name="Liberation Sans", size=10, color="0000FF")
    link_font = Font(name="Liberation Sans", size=10, color="1F5F99", underline="single")
    wrap = Alignment(wrap_text=True, vertical="top")

    wb = Workbook()
    wb.remove(wb.active)

    def sheet(title, header, rows, widths, freeze="B2", links=None):
        ws = wb.create_sheet(title)
        ws.append(header)
        for c in ws[1]:
            c.fill, c.font, c.alignment = head_fill, head_font, Alignment(wrap_text=True, vertical="center")
        for r in rows:
            ws.append([r.get(h) for h in header])
        for row in ws.iter_rows(min_row=2):
            for c in row:
                c.font, c.alignment = body_font, wrap
        for i, w in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(i)].width = w
        ws.freeze_panes = freeze
        if rows:
            ws.auto_filter.ref = f"A1:{get_column_letter(len(header))}{len(rows) + 1}"
        for col, make in (links or {}).items():
            j = header.index(col) + 1
            for i in range(2, len(rows) + 2):
                c = ws.cell(row=i, column=j)
                url = make(c.value)
                if url:
                    c.hyperlink, c.font = url, link_font
        return ws

    by_id = {d["id"]: d for d in records}
    latest = max((str(h.get("date")) for d in records for h in (d.get("history") or [])), default="")

    # Guide
    ws = wb.create_sheet("Guide")
    guide = [
        ("Miżien: claim tracker", None),
        (f"Generated from the claim records by scripts/sheets.py; records as of {latest} (latest research-log date). "
         "Do not edit this workbook: change claims/CC-NNN/claim.yml or the CSV named for each sheet, then run "
         "python scripts/sheets.py --xlsx.", None),
        (None, None), ("SHEETS", None),
        ("Claims", "The claim sheet (data/claims.csv): one row per claim, plus verdict, pledge label, version, "
                   "dates, the worker queue and a link to the claim page."),
        ("Facts", "The fact sheet (data/facts.csv): every figure a check recomputed, from data/cc-nnn/checks.csv. "
                  "Row is CC-NNN:line in that file (header = line 1)."),
        ("Quick checks", "Arithmetic on figures quoted publicly, at intake (data/quick_checks.csv). Calculated is a "
                         "formula where one of the usual operations reproduces it; blue figures are inputs."),
        ("Patterns", "The pattern tags (methodology/pattern-tags.md) and the claims that carry each, finished or "
                     "provisional."),
        ("Themes", "Themes linking several claims (data/themes.csv), with edges counted."),
        ("Edges", "Pairwise links between claims, each through a theme (data/edges.csv)."),
        ("Sources", "Every source recorded for the claims (data/sources.csv)."),
        ("Bodies", "The register of bodies and people (data/bodies.csv), with the claims each made."),
        ("Actors", "Organisations and the claims made by them or their people (data/actors.csv)."),
        ("Queue", "Claims assigned to the nightly workers (data/queue.csv), with attempts and blockers."),
        (None, None), ("RULES", None),
        ("Source of truth", "claims/CC-NNN/claim.yml. Verdicts follow methodology/verdict-scale.md."),
        ("Right of reply", "Sought only for Not substantiated, Misleading or Contradicted (pledges: Not measurable, "
                           "Off track, Missed). A draft verdict may appear on the project's own site, marked as a "
                           "draft; do not circulate a Misleading or Contradicted verdict elsewhere before the "
                           "right-of-reply deadline."),
        ("Wording status", "Verbatim found: the speaker's own words from a primary source. Paraphrase: locate quote: "
                           "a report or summary only; no report until the wording is found."),
        ("Sub judice", "CC-002 (Comino) is before a planning tribunal: the science only."),
    ]
    for a, b in guide:
        ws.append([a, b])
    ws["A1"].font = Font(name="Liberation Sans", bold=True, size=14, color="14452F")
    for r in ws.iter_rows(min_row=2):
        for c in r:
            c.font, c.alignment = body_font, wrap
    for label in ("SHEETS", "RULES"):
        for r in ws.iter_rows(min_col=1, max_col=1):
            if r[0].value == label:
                r[0].font = Font(name="Liberation Sans", bold=True, color="14452F")
    ws.column_dimensions["A"].width, ws.column_dimensions["B"].width = 22, 110

    # Claims
    extra = ["Verdict", "Confidence", "Pledge label", "Subtopic", "Said on", "Version", "Last reviewed",
             "Worker", "Attempts", "Last attempt", "Blocker", "Page"]
    rows = claim_rows(records, edges, queue)
    for r in rows:
        d, q = by_id[r["ID"]], queue.get(r["ID"], {})
        r.update({"Verdict": d.get("verdict"), "Confidence": d.get("verdict_confidence"), "Pledge label": pledge_label(d),
                  "Subtopic": d.get("subtopic"), "Said on": str((d.get("claim") or {}).get("date") or ""),
                  "Version": d.get("version"), "Last reviewed": str(d.get("last_reviewed") or ""),
                  "Worker": q.get("Worker"), "Attempts": q.get("Attempts"), "Last attempt": q.get("Last attempt"),
                  "Blocker": q.get("Blocker"), "Page": f"{SITE}/claims/{r['ID']}/"})
    header = CLAIM_COLUMNS + extra
    ws = sheet("Claims", header, rows,
               [9, 16, 24, 48, 42, 34, 30, 20, 26, 18, 10, 12, 40, 12, 12, 9, 40,
                18, 11, 14, 18, 11, 8, 12, 8, 8, 11, 40, 30], freeze="D2",
               links={"Page": lambda v: v})
    n = len(rows) + 1
    col = {h: get_column_letter(header.index(h) + 1) for h in header}
    for h, choices in (("Check status", "Not started,In progress,Drafted,Right of reply,Published"),
                       ("Claim wording status", "Verbatim found,Paraphrase: locate quote"),
                       ("Data readiness", "High,Medium,Low")):
        dv = DataValidation(type="list", formula1=f'"{choices}"', allow_blank=True)
        dv.add(f"{col[h]}2:{col[h]}{n}")
        ws.add_data_validation(dv)
    pale, amber, cream = PatternFill("solid", fgColor="E6EFE8"), PatternFill("solid", fgColor="F6E3B4"), \
        PatternFill("solid", fgColor="F6F4EE")
    ws.conditional_formatting.add(f"{col['Claim wording status']}2:{col['Claim wording status']}{n}",
                                  CellIsRule(operator="equal", formula=['"Verbatim found"'], fill=pale))
    ws.conditional_formatting.add(f"{col['Claim wording status']}2:{col['Claim wording status']}{n}",
                                  CellIsRule(operator="equal", formula=['"Paraphrase: locate quote"'], fill=amber))
    ws.conditional_formatting.add(f"{col['Check status']}2:{col['Check status']}{n}",
                                  CellIsRule(operator="equal", formula=['"Drafted"'], fill=pale))
    ws.conditional_formatting.add(f"{col['Check status']}2:{col['Check status']}{n}",
                                  CellIsRule(operator="equal", formula=['"In progress"'], fill=cream))

    # Facts
    sheet("Facts", FACT_COLUMNS, fact_rows(), [9, 12, 60, 14, 12, 40, 40, 40], freeze="C2",
          links={"ID": lambda v: f"{SITE}/claims/{v}/" if v else None})

    # Quick checks, with formulas where the arithmetic is recognised
    qc = read_csv("quick_checks.csv")
    qheader = list(qc[0].keys()) if qc else []
    ws = sheet("Quick checks", qheader, qc, [34, 9, 30, 12, 30, 12, 14, 16, 20, 60], freeze="B2")
    for i, r in enumerate(qc, start=2):
        for key in ("Value 1", "Value 2", "Figure as stated publicly"):
            c = ws.cell(row=i, column=qheader.index(key) + 1)
            try:
                c.value = float(c.value) if "." in str(c.value) else int(c.value)
                c.font = input_font
            except (TypeError, ValueError):
                pass
        f = quick_check_formula(r, i)
        if f:
            c = ws.cell(row=i, column=qheader.index("Calculated") + 1)
            c.value = f
            if str(r["Calculated"]).endswith("%"):
                c.number_format = "0.0%"

    # Patterns
    sheet("Patterns", ["Tag", "Meaning", "Claims (finished reports)", "Claims (provisional)", "Claims (count)",
                       "Verdicts of tagged claims"], pattern_rows(records), [28, 60, 40, 30, 10, 50], freeze="B2")

    # Themes and edges
    trows = themes_recounted(themes, edges)
    sheet("Themes", list(trows[0].keys()) if trows else [], trows, [9, 30, 40, 20, 18, 80, 10], freeze="B2")
    sheet("Edges", ["From", "To", "Theme ID", "Theme", "Link type", "Strength"], edges, [10, 10, 9, 36, 22, 20],
          freeze="A2")

    # Sources
    src = read_csv("sources.csv")
    sheet("Sources", list(src[0].keys()) if src else [], src, [7, 14, 52, 26, 14, 20, 50, 50], freeze="C2",
          links={"URL": lambda v: v if str(v).startswith("http") else None})

    # Bodies, with their claims
    idx = register.alias_index(reg)
    made = collections.defaultdict(list)
    for d in records:
        for bid in register.resolve(d, reg, idx)[0]:
            made[bid].append(d["id"])
    brows = [{"ID": b["id"], "Name": b["name"], "Kind": b["kind"], "Type": register.TYPES.get(b["type"], b["type"]),
              "Parent": reg[b["parent"]]["name"] if b["parent"] in reg else "", "Role": b["role"] or "",
              "Claims": ", ".join(made.get(b["id"], [])), "Claims (count)": len(made.get(b["id"], []))}
             for b in reg.values()]
    sheet("Bodies", ["ID", "Name", "Kind", "Type", "Parent", "Role", "Claims", "Claims (count)"], brows,
          [26, 36, 12, 26, 30, 24, 40, 9], freeze="C2")
    sheet("Actors", ACTOR_COLUMNS, actor_rows(records, reg), [44, 60, 30, 10], freeze="B2")

    # Queue, with each claim's status
    qrows = [{**r, "Status": by_id.get(r["ID"], {}).get("status")} for r in read_csv("queue.csv")]
    sheet("Queue", ["ID", "Worker", "Status", "Added", "Note", "Attempts", "Last attempt", "Blocker"], qrows,
          [9, 8, 12, 11, 30, 9, 12, 90], freeze="B2",
          links={"ID": lambda v: f"{SITE}/claims/{v}/" if v else None})

    wb.properties.creator = wb.properties.lastModifiedBy = "Miżien (scripts/sheets.py)"
    wb.properties.title = "Miżien claim tracker"
    import datetime
    fixed = datetime.datetime(2026, 1, 1)
    wb.properties.created = wb.properties.modified = fixed
    buf = io.BytesIO()
    wb.save(buf)
    _write_stable_zip(buf.getvalue(), path)
    return path


def _write_stable_zip(data, path):
    """Re-pack the workbook with fixed timestamps, so the same records give the same bytes."""
    src = zipfile.ZipFile(io.BytesIO(data))
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for info in src.infolist():
            zi = zipfile.ZipInfo(info.filename, date_time=(1980, 1, 1, 0, 0, 0))
            zi.compress_type, zi.external_attr = zipfile.ZIP_DEFLATED, 0o600 << 16
            body = src.read(info.filename)
            if info.filename == "docProps/core.xml":   # openpyxl stamps the save time into the modified date
                body = re.sub(rb"(<dcterms:modified[^>]*>)[^<]*(</dcterms:modified>)", rb"\g<1>2026-01-01T00:00:00Z\g<2>", body)
            z.writestr(zi, body)
    data = out.getvalue()
    if not path.is_file() or path.read_bytes() != data:
        path.write_bytes(data)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    records = load_records()
    changed = write_text_sheets(records)
    if "--xlsx" in argv:
        before = (ROOT / "data" / "candidates.xlsx").read_bytes() if (ROOT / "data" / "candidates.xlsx").is_file() else b""
        write_workbook(records)
        if (ROOT / "data" / "candidates.xlsx").read_bytes() != before:
            changed.append("data/candidates.xlsx")
    print("sheets: " + (", ".join(changed) + " updated" if changed else "all current"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
